parameters:
    ibraza.logo_path: '%kernel.project_dir%/public/images/logo_ibraza.png'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\EmailService:
        arguments:
            $logoPath: '%ibraza.logo_path%'
