parameters:
    ibraza.logo_path: '%kernel.project_dir%/public/images/logo_ibraza.png'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\EmailService:
        arguments:
            $logoPath: '%ibraza.logo_path%'

    App\Service\BrevoService:
        arguments:
            $brevoApiKey: '%env(BREVO_API_KEY)%'
            $brevoListId: '%env(BREVO_LIST_ID)%'

    services:
    App\Service\BrevoMailerService:
        arguments:
            $apiKey: '%env(BREVO_API_KEY)%'
